<a href="https://colab.research.google.com/github/ppopdesk/RLProj_SAC/blob/main/Copy_of_Assign1_RLbots.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is the main package for scientific computing in Python. It is maintained by a large community (www.numpy.org). In this exercise you will learn several key numpy functions such as np.exp, np.log, and np.reshape. You will need to know how to use these functions for future assignments.


**CREATE A NUMPY ARRAY FROM A LIST**

In [1]:
import numpy as np 
#create a numpy array of numbers {0,1,2,3,4,5,6} and print the array

#YOUR CODE STARTS HERE 
i = [0,1,2,3,4,5,6]
arr = np.array(i)
print(arr)

#YOUR CODE ENDS HERE



[0 1 2 3 4 5 6]


**PRINT ALTERNATE ELEMENTS OF A NUMPY ARRAY**

In [2]:
import numpy as np

#create a numpy array of number {7,8,5,10,1,2,3,4} and print alternate elements of this array using for loop.

#YOUR CODE STARTS HERE
i = [0,1,2,3,4,5,6]
arr = np.array(i)
for i in range(0,len(arr),2):
  print(i)
#YOUR CODE ENDS HERE

0
2
4
6


**ALTERNATE ELEMENTS USING SLICING**

In [4]:
import numpy as np 
#create a numpy array of number {7,8,5,10,1,2,3,4} and print alternate elements of this array using slicing.Google for more information.

#YOUR CODE STARTS HERE
arr = np.array([7,8,5,10,1,2,3,4])
print(arr[1::2])
#YOUR CODE ENDS HERE


[ 8 10  2  4]


**NUMPY COPY VS NUMPY VIEW**

In [ ]:
import numpy as np 
# create a numpy array of numbers {10,9,11,2,3,4,5} . Create a copy of this array using numpy copy. Then multiply the copy array by 2 . print both the arrays

#YOUR CODE STARTS HERE
arr = np.array([10,9,11,2,3,4,5])
arr1 = np.copy(arr)
arr1 = arr1*2
print(arr)
print(arr1)
#YOUR CODE ENDS HERE


# create a numpy array of numbers {10,9,11,2,3,4,5} . Create a view of this array using numpy view. Then multiply the view array by 2 . print both the arrays

#YOUR CODE STARTS HERE
arr = np.array([10,9,11,2,3,4,5])
arr1 = arr.view()
for i in range(len(arr1)):
  arr[i] *=2
print(arr)
print(arr1)

#YOUR CODE ENDS HERE


**SHAPE AND RESHAPE**

In [5]:
import numpy as np 
#create a numpy array of numbers {1,2,3,4,5,6,7,8}. Print the shape of this array.Convert this array to a new array of size 4*2 . Print the shape of new array
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.shape)
arr=arr.reshape(4,2)
print(arr.shape)


(8,)
(4, 2)


**SIGMOID FUNCTION USING NUMPY ARRAY**

Before using np.exp(), you will use math.exp() to implement the sigmoid 

function. You will then see why np.exp() is preferable to math.exp().



Build a function that returns the sigmoid of a real number x. Use math.exp(x) for the exponential function.
Search for sigmoid function on internet

To refer to a function belonging to a specific package you could call it using package_name.function(). Run the code below to see an example with math.exp().

In [6]:
import math

# GRADED FUNCTION: basic_sigmoid

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    # (≈ 1 line of code)
    # s = 
    # YOUR CODE STARTS HERE
    e = math.exp(x)
    s = e/(1+e)
    
    # YOUR CODE ENDS HERE
    
    return s

Actually, we rarely use the "math" library in deep learning because the inputs of the functions are real numbers. In deep learning we mostly use matrices and vectors. This is why numpy is more useful.

In [ ]:
### One reason why we use "numpy" instead of "math" in Deep Learning ###

x = [1, 2, 3] # x becomes a python list object
basic_sigmoid(x) # you will see this give an error when you run it, because x is a vector.

In fact, if  𝑥=(𝑥1,𝑥2,...,𝑥𝑛)  is a row vector then np.exp(x) will apply the exponential function to every element of x. The output will thus be: np.exp(x) = (e^{x_1}, e^{x_2}, ..., e^{x_n})

In [7]:
import numpy as np

# example of np.exp
t_x = np.array([1, 2, 3])
print(np.exp(t_x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


**SIGMOID FUNCTION**

Implement the sigmoid function using numpy.

Instructions: x could now be either a real number, a vector, or a matrix. The data structures we use in numpy to represent these shapes (vectors, matrices...) are called numpy arrays. You don't need to know more for now

In [8]:
# GRADED FUNCTION: sigmoid

def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    # (≈ 1 line of code)
    # s = 
    # YOUR CODE STARTS HERE
    e = np.exp(x)
    s = e/(1+e)
    # YOUR CODE ENDS HERE
    
    return s

**TRANSPOSE OF A MATRIX USING FOR LOOP**

Input : A 3 X 3 sample matrix of your choice

Output : Transpose of that matrix

Note : Use For loop and numpy library

In [9]:
import numpy as np
#specify sample input here using numpy library
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#insert code here
for i in range(3):
  for j in range(i+1,3):
    arr[i][j],arr[j][i]=arr[j][i],arr[i][j]
print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


**PANDAS**

Pandas framework is used to edit and access dataframes making them more accessible while using in machine learning and similiar fields of study. 
Here are three questions based upon the same to help you develop a basic idea.

**WORKING WITH STRINGS**

Write a pandas program to perform some operations on a series of strings as follows:

1. remove vowels from all strings
2. convert the strings to lowercase
3. convert the first and third(if it exists) character to upper case
4. sort the series
Note : The series of string will be in a csv file.
You need to code with a sample input from your end and specify it

In [10]:
import pandas as pd
#code here
dict1={"strings":['Aryan','Utkarsh','Rishabh','Rohan','Eesh']}
df=pd.DataFrame(dict1)
n1=len(df['strings'])
n2=0
for i in range (0,n1):
    n2=len(df['strings'][i])
    s=df['strings'][i]
    s1=""
    v=['a','e','i','o','u']
    for j in range (0,n2):
        if s[j].lower() not in v:
            s1+=s[j]
    df['strings'][i]=s1

for k in range (0,n1):
  df['strings'][k]=df['strings'][k].lower()
  for p in range (0,len(df['strings'][k])):
    if (p==0 or p==2):
      df['strings'][k]=df['strings'][k].replace(df['strings'][k][p],df['strings'][k][p].upper())
 
df=df['strings'].sort_values(ascending=True)
print(df)



3      RhN
2    RsHbH
0      RyN
4       Sh
1    TkRsh
Name: strings, dtype: object


**DICTIONARY PROBLEM**

Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels. 

Here is a example for your reference:


Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


Expected Output:


attempts name qualify score


a 1 Anastasia yes 12.5


b 3 Dima no 9.0


i 2 Kevin no 8.0


j 1 Jonas yes 19.

Note : The data will again we saved in a input file that needs to be specified by you. The data will be present in format mentioned. 

**FOLLOW UP FOR Q2 on Pandas**

Write a pandas program to select the rows with number of attempts > 2 for the same input dataframe

In [11]:
#answer here
import pandas as pd
examdata={"name":['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
          "score":[12.5, 9, 16.5,21, 9, 20, 14.5,16, 8, 19],
          "attempts": [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
          "qualify": ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df=pd.DataFrame(examdata)
df.loc[(df['attempts']>2)]

name  score  attempts qualify
1     Dima    9.0         3      no
3    James   21.0         3      no
5  Michael   20.0         3     yes